name: cc25-box-online-multiplayer-hosted

services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    command: node index.js -m 4 ${SERVER_PARAMS}

  caia-players:
    build:
      context: ..
      dockerfile: docker/client/Dockerfile
    command: ./start-caia-players.sh ${CLIENT_PARAMS}

volumes:
  caddy_data:
  caddy_config:
